# Generated by Django 4.2.6 on 2023-12-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('coname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('copopulation', models.IntegerField()),
                ('coarea', models.IntegerField()),
                ('copm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caname', models.CharField(max_length=200)),
                ('capopulation', models.IntegerField()),
                ('caarea', models.IntegerField()),
                ('cacode', models.IntegerField()),
                ('coname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
